In [2]:
#first run this cell
#you will get an url ,click on thaT ,allow permission,copy the authorisation codeband paste it
from google.colab import drive
drive.mount("/content/drive",force_remount=True)

Mounted at /content/drive


PROJECT ON FRAUD DETECTION ON CREDIT CARDS RETURNS

IMPORTING THE OS

In [3]:
import os
os.chdir("/content/drive/MyDrive/fraud detection using ml")
os.listdir()

['identity_file.csv', 'transaction_file.csv', 'fraud_detection.ipynb']

IMPORTING THE LIBRARIES

In [4]:
import pandas as pd
import numpy as np

In [5]:
pd.set_option('display.max_column', 400)
pd.set_option('display.max_rows', 100)

IMPORTING THE DATASET

In [6]:
train_transaction= pd.read_csv("transaction_file.csv")
train_identity = pd.read_csv('identity_file.csv')

In [7]:
train = pd.merge(train_transaction, train_identity, on='TransactionID', how='left')


In [8]:
#To fill the missing NaN values 
train = train.fillna(-999)

In [9]:
print(train.shape)


(590540, 434)


In [10]:
train.head()

TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  card1  \
0        2987000        0          86400            68.5         W  13926   
1        2987001        0          86401            29.0         W   2755   
2        2987002        0          86469            59.0         W   4663   
3        2987003        0          86499            50.0         W  18132   
4        2987004        0          86506            50.0         H   4497   

   card2  card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
0 -999.0  150.0    discover  142.0  credit  315.0   87.0   19.0 -999.0   
1  404.0  150.0  mastercard  102.0  credit  325.0   87.0 -999.0 -999.0   
2  490.0  150.0        visa  166.0   debit  330.0   87.0  287.0 -999.0   
3  567.0  150.0  mastercard  117.0   debit  476.0   87.0 -999.0 -999.0   
4  514.0  150.0  mastercard  102.0  credit  420.0   87.0 -999.0 -999.0   

  P_emaildomain R_emaildomain   C1   C2   C3   C4   C5   C6   C7   C8   C9  \
0          -999          -999  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
1     gmail.com          -999  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
2   outlook.com          -999  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
3     yahoo.com          -999  2.0  5.0  0.0  0.0  0.0  4.0  0.0  0.0  1.0   
4     gmail.com          -999  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   

   C10  C11  C12   C13  C14     D1     D2     D3     D4     D5     D6     D7  \
0  0.0  2.0  0.0   1.0  1.0   14.0 -999.0   13.0 -999.0 -999.0 -999.0 -999.0   
1  0.0  1.0  0.0   1.0  1.0    0.0 -999.0 -999.0    0.0 -999.0 -999.0 -999.0   
2  0.0  1.0  0.0   1.0  1.0    0.0 -999.0 -999.0    0.0 -999.0 -999.0 -999.0   
3  0.0  1.0  0.0  25.0  1.0  112.0  112.0    0.0   94.0    0.0 -999.0 -999.0   
4  1.0  1.0  0.0   1.0  1.0    0.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0   

      D8     D9    D10    D11    D12    D13    D14    D15    M1    M2    M3  \
0 -999.0 -999.0   13.0   13.0 -999.0 -999.0 -999.0    0.0     T     T     T   
1 -999.0 -999.0    0.0 -999.0 -999.0 -999.0 -999.0    0.0  -999  -999  -999   
2 -999.0 -999.0    0.0  315.0 -999.0 -999.0 -999.0  315.0     T     T     T   
3 -999.0 -999.0   84.0 -999.0 -999.0 -999.0 -999.0  111.0  -999  -999  -999   
4 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0  -999  -999  -999   

     M4    M5    M6    M7    M8    M9     V1     V2     V3     V4     V5  \
0    M2     F     T  -999  -999  -999    1.0    1.0    1.0    1.0    1.0   
1    M0     T     T  -999  -999  -999 -999.0 -999.0 -999.0 -999.0 -999.0   
2    M0     F     F     F     F     F    1.0    1.0    1.0    1.0    1.0   
3    M0     T     F  -999  -999  -999 -999.0 -999.0 -999.0 -999.0 -999.0   
4  -999  -999  -999  -999  -999  -999 -999.0 -999.0 -999.0 -999.0 -999.0   

      V6     V7     V8     V9    V10    V11    V12    V13    V14    V15  \
0    1.0    1.0    1.0    1.0    0.0    0.0    1.0    1.0    1.0    0.0   
1 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0    0.0    0.0    1.0    0.0   
2    1.0    1.0    1.0    1.0    0.0    0.0    1.0    1.0    1.0    0.0   
3 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0    1.0    1.0    1.0    0.0   
4 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0   

     V16    V17    V18    V19    V20    V21    V22    V23    V24    V25  \
0    0.0    0.0    0.0    1.0    1.0    0.0    0.0    1.0    1.0    1.0   
1    0.0    0.0    0.0    1.0    1.0    0.0    0.0    1.0    1.0    1.0   
2    0.0    0.0    0.0    1.0    1.0    0.0    0.0    1.0    1.0    1.0   
3    0.0    0.0    0.0    1.0    1.0    0.0    0.0    1.0    1.0    1.0   
4 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0 -999.0   

     V26    V27    V28    V29    V30    V31    V32    V33    V34    V35  \
0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0 -999.0   
1    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
3    1.0   

In [11]:
y = train['isFraud']
X = train.drop(columns=['isFraud'])



In [12]:
normal=train[train["isFraud"]==0]
fraud=train[train["isFraud"]==1]

In [13]:
print(normal.shape)
print(fraud.shape)

(569877, 434)
(20663, 434)


DATA PREPROCESSING

In [14]:
#preprocessing
from sklearn import preprocessing
for f in X.columns:
    if X[f].dtype=='object' :
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(X[f].values))
        X[f] = lbl.transform(list(X[f].values))     

FEATURE SCALING

In [15]:
from sklearn.preprocessing import StandardScaler
SC_X=StandardScaler().fit_transform(X)

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.99999)
PC_X = pca.fit_transform(SC_X)

PERFORMING SAMPLING TECHNIQUES TO SOLVE THE DATA IMBALANCY PROBLEM

In [17]:
#solving class imbalancy problem
#using undersampling method
from imblearn.under_sampling import NearMiss


/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [18]:
# implementing undersampling for handling imbalanced
nM = NearMiss(random_state=42)
X_res,y_res=nM.fit_resample(PC_X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [19]:
X_res.shape,y_res.shape

((41326, 182), (41326,))

In [20]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y)))
print('Resampled dataset shape {}'.format(Counter(y_res)))

Original dataset shape Counter({0: 569877, 1: 20663})
Resampled dataset shape Counter({0: 20663, 1: 20663})


NOT to be used here, showing it for information purpose only.

In [ ]:
# solving class imbalancy problem 
# using over sampling method
from imblearn.combine import SMOTETomek


In [ ]:
# implementing Oversampling for Handling Imbalanced
smk = SMOTETomek(random_state=42)
X_res,y_res=smk.fit_sample(PC_X,y)

In [ ]:
X_res.shape,y_res.shape

In [ ]:
from collections import Counter
print('Original dataset shape {} '.format(Counter(y)))
print('Resampled dataset shape []'.format(Counter(y_res)))

NOT to be used here, showing it for information purpose only.

In [ ]:
# RandomOverSample to handle imbalanced data  
from imblearn.over_sampling import RandomOverSampler


In [ ]:
os = RandomOverSampler(ratio=1)

In [ ]:
X_res,y_res=os.fit_sample(PC_X,y)

In [ ]:
X_res.shape,y_res.shape

In [ ]:
from collections import Counter
print('Original data set {}'.format(Counter(y)))
print('Resampled data set {}'.format(Counter(y_res)))

In [ ]:
X = X.values
y = y.values

FEATURE SELECTION USING AUTOMATIC BACKWARD ELIMINATION

In [21]:
#try
# FEATURE SELECTION
#Automatic implementations of Backward Elimination in Python with p-value
import statsmodels.api as sm
def backwardElimination(y,x, sl):
    numVars = len(x[0])
    numRows = len(x)
    x = np.append(arr = np.ones( (numRows,1) ).astype(int), values=x, axis=1)
    for i in range(0, numVars):
        print(i,end=' ')
        numVars = len(x[0])
        regressor_OLS = sm.OLS(y, x).fit()
        pVal=regressor_OLS.pvalues.astype(float)
        maxVar = max(pVal)
        if maxVar > sl:
            for j in range(0, numVars):
                if (pVal[j] == maxVar):
                    x = np.delete(x, j, 1)
                    break;
        else:
            break
    print('sup')
    regressor_OLS.summary()
    return x
x_opt=backwardElimination(y_res,X_res,0.05)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 sup


SPLITTING THE DATASET INTO TRAINING AND TEST SET

In [22]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_opt, y_res, test_size = 0.2, random_state = 0)



LOGISTIC REGRESSION MODEL

FITTING THE TRAINING SET INTO LOGISTIC REGRESSION MODEL

In [23]:
# ALGORITHM 1
# classification  -> logistic regression

from sklearn import  linear_model,metrics 

     
# create logistic regression object 
logReg = linear_model.LogisticRegression(max_iter=100000)

   
# train the model using the training sets 
logReg.fit(X_train,y_train)
  
# making predictions on the testing set
y_pred =logReg.predict(X_test) 
   



CONFUSION MATRIX WITH ACCURACY AND LOSS LOG

In [24]:
# comparing actual response values (y_test) with predicted response values (y_pred) 

from sklearn.metrics import confusion_matrix

print("confusion metrics =")
confuse= confusion_matrix(y_test,y_pred)
print(confuse)

print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test,y_pred)*100)

print("loss =\n",metrics.log_loss(y_test,y_pred))



confusion metrics =
[[3839  223]
 [ 414 3790]]
Logistic Regression model accuracy(in %): 92.293733365594
loss =
 2.661671772778253


In [25]:
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred))


0.9224777899476694


SVM MODEL

In [26]:
# ALGORITHM 2
#svm classification
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [27]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [28]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
print("confusion metrics =")
confuse= confusion_matrix(y_test,y_pred)
print(confuse)

print("SVM model accuracy(in %):", metrics.accuracy_score(y_test,y_pred)*100)

print("loss =\n",metrics.log_loss(y_test,y_pred))


confusion metrics =
[[3842  220]
 [ 417 3787]]
SVM model accuracy(in %): 92.293733365594
loss =
 2.6616714825783636


In [29]:
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred))

0.9224211423699914


KNN MODEL

In [30]:
# ALGORITHM 3
# KNN CLASSIFICATION MODEL
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors = 5, metric ='minkowski', p = 2)
classifier.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [32]:

# Predicting the Test set results
y_pred = classifier.predict(X_test)




In [33]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
print("confusion metrics =")
confuse= confusion_matrix(y_test,y_pred)
print(confuse)

print("KNN  model accuracy(in %):", metrics.accuracy_score(y_test,y_pred)*100)

print("loss =\n",metrics.log_loss(y_test,y_pred))

confusion metrics =
[[3925  137]
 [ 680 3524]]
KNN  model accuracy(in %): 90.11613839825793
loss =
 3.4137781102697757


In [34]:
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred))

0.8961220597584234


SVM KERNEL MODEL

In [35]:
# ALGORITHM 4
#svm kernel CLASSIFICATION MODEL
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [37]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score,log_loss
print("confusion metrics =")
confuse= confusion_matrix(y_test,y_pred)
print(confuse)

print("KERNEL SVM model accuracy(in %):", accuracy_score(y_test,y_pred)*100)

print("loss =\n",log_loss(y_test,y_pred))

confusion metrics =
[[3889  173]
 [ 352 3852]]
KERNEL SVM model accuracy(in %): 93.64868134526978
loss =
 2.1936844831458426


In [38]:
from sklearn.metrics import f1_score
print(" f1 score",f1_score(y_pred,y_test))

 f1 score 0.936201239518775
